spring.application.name=departmentcategorizer


spring.h2.console.enabled = true

spring.datasource.url=jdbc:h2:file:D:/cohort 5.0/module 2/RESTFul apis/H2DBData
spring.datasource.username=rahulDB
spring.datasource.password=rahul123

spring.jpa.hibernate.ddl-auto=create